package network.o3.o3wallet

import android.preference.PreferenceManager
import neoutils.Neoutils.generateFromWIF
import neoutils.Neoutils.generateFromPrivateKey
import neoutils.Wallet
import network.o3.o3wallet.Crypto.Decryptor
import network.o3.o3wallet.Crypto.Encryptor
import network.o3.o3wallet.Crypto.EncryptedSettingsRepository
import network.o3.o3wallet.Crypto.EncryptedSettingsRepository.setProperty
import java.lang.Exception
import java.security.SecureRandom

/**
 * Created by drei on 11/22/17.
 */

object Account {
    private var wallet: Wallet? = null
    private var sharedSecretPieceOne: String? = null

    private fun storeEncryptedKeyOnDevice() {
        val wif = wallet!!.wif
        val encryptor = Encryptor()
        val alias = "O3 Key"
        val encryptedWIF = encryptor.encryptText(alias, wif)!!

        val iv = encryptor.getIv()!!
        setProperty(alias, encryptedWIF.toHex(), iv, O3Wallet.appContext!!)
    }

    fun storeColdStorageKeyFragmentOnDevice(keyFragment: String) {
        val alias = "Cold Storage Key Fragment"
        val encryptor = Encryptor()
        val encryptedFragment = encryptor.encryptText(alias, keyFragment)!!
        val iv = encryptor.getIv()!!
        setProperty(alias, encryptedFragment.toHex(), iv, O3Wallet.appContext!!)
    }

    fun getColdStorageKeyFragmentOnDevice(): String {
        val alias = "Cold Storage Key Fragment"
        val storedVal = EncryptedSettingsRepository.getProperty(alias, O3Wallet.appContext!!)
        if (storedVal?.data == null) {
            return ""
        }
        val storedEncryptedFragment = storedVal?.data?.hexStringToByteArray()
        if (storedEncryptedFragment == null || storedEncryptedFragment.size == 0) {
            return ""
        }
        val storedIv = storedVal?.iv!!
        val decrypted = Decryptor().decrypt(alias, storedEncryptedFragment, storedIv)
        return decrypted
    }

    fun removeColdStorageKeyFragment() {
        storeColdStorageKeyFragmentOnDevice("")
    }

    fun isEncryptedWalletPresent(): Boolean {
        val alias = "O3 Key"
        val storedVal = EncryptedSettingsRepository.getProperty(alias, O3Wallet.appContext!!)
        if (storedVal?.data == null) {
            return false
        }
        val storedEncryptedWIF = storedVal?.data?.hexStringToByteArray()
        if (storedEncryptedWIF == null || storedEncryptedWIF.size == 0 || !Decryptor().keyStoreEntryExists("O3 Key")) {
            return false
        }
        return true
    }

    fun restoreWalletFromDevice() {
        val alias = "O3 Key"
        val storedVal = EncryptedSettingsRepository.getProperty(alias, O3Wallet.appContext!!)
        val storedEncryptedWIF = storedVal?.data?.hexStringToByteArray()!!
        val storedIv = storedVal?.iv!!
        val decrypted = Decryptor().decrypt(alias, storedEncryptedWIF, storedIv)
        wallet = generateFromWIF(decrypted)
    }

    fun createNewWallet() {
        val random = SecureRandom()
        var bytes = ByteArray(32)
        random.nextBytes(bytes)
        val hex = bytes.toHex()
        wallet = generateFromPrivateKey(hex)
        storeEncryptedKeyOnDevice()
    }

    fun deleteKeyFromDevice() {
        val alias = "O3 Key"
        setProperty(alias, "", kotlin.ByteArray(0), O3Wallet.appContext!!)
    }
    
    fun fromWIF(wif: String): Boolean{
        //Java does not support multiple return values from function.
        //The function that is generated by go mobile bind. If the second return value is Error type, it will throw the generic exception
        try {
            wallet = generateFromWIF(wif)
        } catch (e: Exception) {
            return false
        }

        storeEncryptedKeyOnDevice()
        return true
    }

    fun getWallet(): Wallet? {
        return wallet
    }
}
